### ISSUE TITLE
For the Measure tool, change to metric system

### ISSUE THREAD

**Issue by chamthesleeptalker** [lkpanganiban/ppaprototype#10]
or, as mentioned in the conceptual screens,

**Comment by lkpanganiban** [comment]
edit the var measureControl variable in map.js into the following code:
```
var measurecontrol = L.control.measure({
    activeColor: "#D20B0B",
    completedColor: "#123DF5",
    primaryLengthUnit: 'meters',
    secondaryLengthUnit: 'feet',
    primaryAreaUnit: 'sqmeters',
    secondaryAreaUnit: 'sqfeet'
});
```

**Comment by chamthesleeptalker** [comment]
is this working. can't make it work.

**Comment by lkpanganiban** [comment]
it should be working. yung nakita ko sa code may dalawang instance yung measure control na variable i-delete mo yung isa.

**Comment by chamthesleeptalker** [comment]
saw the double declaration.
